blog/urls.py
from django.urls import path
from . import views as v
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # path('', v.PostList.as_view(), name='post_list'),
    path('', v.post_list, name='post_list'),
    path('tag/<slug:tag_slug>', v.post_list, name='post_list_by_tag'),
    path('<int:post_id>/share', v.post_share, name='post_share'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', v.post_detail, name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', v.post_search, name='post_search'),
]

myblogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.CharField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()  # default manager
    published = PublishedManager()  # custom manager

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[
                            self.publish.year,
                            self.publish.month,
                            self.publish.day,
                            self.slug
                       ])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=200)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.views.generic import ListView
from taggit.models import Tag
from django.db.models import Count

from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            # search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
                # similarity=TrigramSimilarity('title', query)
            ).filter(search=search_query).order_by('-rank')

    return render(request, 'blog/post_search.html',
                  {'form': form,
                   'query': query,
                   'results': results})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(data)
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'\
                .format(data['name'], data['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'\
                .format(post.title, post_url, data['name'], data['comments'])

            try:
                send_mail(subject, message, data['email'], [data['to']])
                sent = True
            except Exception as ex:
                print(ex)

    else:
        form = EmailPostForm()
    return render(request, 'blog/post_share.html', {'post': post, 'form': form, 'sent': sent})


class PostList(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post_list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post_list.html',
                  {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day
                             )
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        print(comment_form)
        if comment_form.is_valid():
            # create comment object bu don't save it yet
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post_detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts
                   })

blog/templates/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load static %}
<!--%{ load static from staticfiles %}-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'blog.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>

<nav>
    <ul>
        <li><a href="{% url 'blog:post_list' %}">HK</a></li>
        <li>
            <form action="{% url 'blog:post_search' %}" method="get">
                <input class="query" type="text" name="query">
                <input type="submit" value="Search">
            </form>
        </li>
        <li><a href="{% url 'blog:post_list' %}">Latest</a></li>
        <li><a href="{% url 'blog:post_feed' %}">RSS</a></li>
        <li><a href="{% url 'blog:post_list' %}">Contact</a></li>
    </ul>
</nav>

    <div class="wrapper">
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
<!--            <h3>My Blog</h3>-->
            <p>This is my blog. I have written <span class="no_of_posts">{% total_posts %}</span> posts till now</p>
            <p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>

            <h3>Latest Posts</h3>
            {% show_latest_posts 4 %}
            <h3>Most Commented Posts</h3>
            {% get_most_commented_posts as most_commented_posts %}
            <ul>
                {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
                {% endfor %}
            </ul>

            <h4><a href="{% url 'blog:post_search' %}">Search for posts</a></h4>

        </div>


    </div>

</body>
</html>

blog/templates/blog/paginator.html
<div class="pagination">
        <span class="step-links">
            {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
            {% endif %}

            <span class="current">
                Page {{ page.number }} of {{ page.paginator.num_pages }}
            </span>

            {% if page.has_next %}
                   <a href="?page={{page.next_page_number}}">Next</a>
            {% endif %}

        </span>

    </div>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block detail %}My Blog {% endblock %}

{% block content %}
    <h1>{{post.title}}</h1>
    <p class="date">
        Published {{post.publish}} by {{post.author}}
    </p>
<!--    {{post.body|linebreaks}}-->
    {{post.body|markdown}}
    <p><a href="{% url 'blog:post_share' post.id %}">Share this Post</a></p>

    <h2>Similar Posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        <p>There are no similar posts yet</p>
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment {{ total_comments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
<!--                Comment {{ forloop.counter }} by -->
                {{ comment.name }} | {{ comment.created }}
            </p>
            {{ comment.body | linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments for the post yet</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="" method="POST">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p><input type="submit" value="Add Comment"></p>
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post_latest.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block title %}My Blog {% endblock %}

{% block content %}
<!--    <h1>My Blogs</h1>-->
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <div class="post">
            <h2 class="title">
                <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
            </h2>
            <p class="tags">Tags:
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p class="date">Published {{post.publish}} by <span class="author">{{post.author}}</span></p>
    <!--        {{post.body|truncatewords:30|linebreaks}}-->
            <p> {{ post.body|markdown|truncatewords_html:30 }} </p>

        </div>

    {% endfor %}

    <br>

<!--    {% include "./paginator.html" with page=page_obj %}-->
    <!--    for CBV -->
    {% include "./paginator.html" with page=posts %}
    <!--for FBV-->

{% endblock %}

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|truncatewords:5 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}

        <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="{% url 'blog:post_search' %}" method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
        </form>
    {% endif %}
    <p><a href="{% url 'blog:post_list' %}">Back to Home</a></p>

{% endblock %}

blog/templates/blog/post_share.html
{% extends 'base.html' %}

{% block detail %}Share a Post {% endblock %}

{% block content %}

    {% if sent %}
        <h1>Email successfully sent</h1>
        <p>"{{post.title}}" was successfully sent to {{ form.cleaned_data.to }}</p>
    {% else %}
        <h1>Share "{{post.title}}" by email</h1>
        <form action="{% url 'blog:post_share' post.id %}" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            {% if form.errors %}
                {% for field in form %}
                    <div>
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                    </div>
                {% endfor %}
            {% endif %}
            <input type="submit" value="Send E-mail">
        </form>
    {% endif %}

{% endblock %}